// ─── AUTH ─────────────────────────────────────────────────────────────────────
export type UserRole = 'admin' | 'manager' | 'viewer' | 'customer';

export interface AuthUser {
  id: string;
  email: string;
  role: UserRole; // from user_metadata.role
}

// ─── ADMIN TEAM ───────────────────────────────────────────────────────────────
export type AdminRole = 'admin' | 'manager' | 'viewer';

export interface AdminUser {
  id: string;
  email: string;
  full_name?: string;
  role: AdminRole;
  created_at: string;
  last_sign_in_at?: string;
}

// ─── ORDER STATUS ─────────────────────────────────────────────────────────────
export type OrderStatus =
  | 'draft'
  | 'confirmado'
  | 'produccion'
  | 'listo_envio'
  | 'enviado'
  | 'cancelado';

// ─── TARIFA ───────────────────────────────────────────────────────────────────
export interface TarifaPrecio {
  tarifa_id: string;
  sku: string;
  precio: number;
}

export interface Tarifa {
  id: string;
  nombre: string;
  descripcion?: string;
  multiplicador: number;           // fallback: shopify_price × multiplicador
  activo: boolean;
  created_at: string;
  hidden_products: string[];       // Shopify product IDs hidden for this tier
  minimum_order_value: number;     // minimum order total in EUR (0 = no minimum)
  pack_size: number;               // quantity must be multiple of this (1 = no restriction)
  precios?: TarifaPrecio[];        // included when fetching detail view
}

// ─── CUSTOMER ────────────────────────────────────────────────────────────────
// Mirrors the `customers` table
export interface Customer {
  id: string;                      // UUID
  auth_user_id: string;            // reference to auth.users
  company_name: string;
  contacto_nombre: string;
  email: string;
  telefono?: string;
  direccion_envio: {
    street: string;
    city: string;
    postal_code: string;
    country: string;
  };
  nif_cif: string;
  estado: 'active' | 'inactive';
  tarifa_id?: string;
  descuento_pct: number;           // 0–100, additional discount on top of the tier
  tarifa?: Tarifa;                 // optional join
  created_at: string;
}

// ─── ORDER ITEM ───────────────────────────────────────────────────────────────
// Mirrors the `order_items` table
// weight always in KG (backend converts from Shopify)
export interface OrderItem {
  id: string;
  order_id: string;
  sku: string;
  nombre_producto: string;
  cantidad: number;
  precio_unitario: number;         // locked at add time
  peso_unitario: number;           // KG, locked at add time
  peso_total_linea: number;        // generated by DB (cantidad * peso_unitario)
}

// ─── ORDER ───────────────────────────────────────────────────────────────────
// Mirrors the `orders` table
export interface Order {
  id: string;                      // UUID — primary identifier
  customer_id: string;
  status: OrderStatus;
  total_productos: number;
  peso_total: number;              // KG
  coste_envio_estimado?: number;
  coste_envio_final?: number;
  packlink_shipment_id?: string;
  tracking_url?: string;           // URL only, no separate tracking_number
  created_at: string;
  // optional joins (when selecting with customer)
  customer?: Customer;
  order_items?: OrderItem[];
}

// ─── SHOPIFY PRODUCT ──────────────────────────────────────────────────────────
// Response from GET /api/products (full catalogue)
// weight always in KG (converted by backend)
export interface Product {
  sku: string;
  nombre_producto: string;
  variante?: string;
  precio_mayorista: number;
  peso_kg: number;                 // always KG
  imagen_url?: string;
}

// ─── DRAFT (local state when creating an order) ───────────────────────────────
// Only exists on the client, never persisted until confirmed
export interface DraftItem {
  sku: string;
  nombre_producto: string;
  cantidad: number;
  precio_unitario: number;
  peso_unitario: number;           // KG
}

export interface CreateOrderPayload {
  customer_id: string;
  items: DraftItem[];
  coste_envio_estimado?: number;
}

// ─── API RESPONSES ────────────────────────────────────────────────────────────
export interface ApiResponse<T> {
  data?: T;
  error?: string;
}
